넘파이 연산 복습

In [1]:
import numpy as np

A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

B = np.array([
    [1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [4, 4, 4, 4, 4],
])

In [2]:
A + B

array([[4, 4, 3, 4, 2],
       [7, 4, 4, 5, 3],
       [6, 6, 5, 6, 4],
       [7, 5, 8, 7, 5]])

In [3]:
A - B

array([[ 2,  2,  1,  2,  0],
       [ 3,  0,  0,  1, -1],
       [ 0,  0, -1,  0, -2],
       [-1, -3,  0, -1, -3]])

In [4]:
A * B

array([[ 3,  3,  2,  3,  1],
       [10,  4,  4,  6,  2],
       [ 9,  9,  6,  9,  3],
       [12,  4, 16, 12,  4]])

In [5]:
A / B

array([[3.        , 3.        , 2.        , 3.        , 1.        ],
       [2.5       , 1.        , 1.        , 1.5       , 0.5       ],
       [1.        , 1.        , 0.66666667, 1.        , 0.33333333],
       [0.75      , 0.25      , 1.        , 0.75      , 0.25      ]])

보시는 것과 같이 각 연산이 같은 행과 열에 있는 원소들에 적용된 걸 확인할 수 있습니다. 같은 위치의 원소들에 연산이 적용되기 때문에 항상 연산 앞과 뒤에 오는 행렬들의 차원이 일치해야만 합니다. 그렇지 않으면 오류가 나게 되죠.

numpy에서는 비어있는 값/요소를 nan으로 표시하는데요. 사칙 연산의 앞이나 뒤 행렬 중 하나라도 nan 값이 있으면 결괏값에 원소도 nan으로 표시가 됩니다.

In [6]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, np.nan, 3, 1],
    [3, 1, 4, 3, 1],
])

B = np.array([
    [1, np.nan, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [np.nan, 4, 4, 4, 4],
])

In [7]:
A + B

array([[ 4., nan,  3.,  4.,  2.],
       [ 7.,  4.,  4.,  5.,  3.],
       [ 6.,  6., nan,  6.,  4.],
       [nan,  5.,  8.,  7.,  5.]])

넘파이 행렬 곱셈

스칼라 곱
- numpy 행렬 모든 원소에 하나의 숫자를 곱해주고 싶을 때는 
-그냥 행렬과 숫자를 * 연산자를 사용해서 곱해주면 됩니다. 이렇게 말이죠

In [9]:
A

array([[ 3.,  3.,  2.,  3.,  1.],
       [ 5.,  2.,  2.,  3.,  1.],
       [ 3.,  3., nan,  3.,  1.],
       [ 3.,  1.,  4.,  3.,  1.]])

In [8]:
5 * A

array([[15., 15., 10., 15.,  5.],
       [25., 10., 10., 15.,  5.],
       [15., 15., nan, 15.,  5.],
       [15.,  5., 20., 15.,  5.]])

@ 연산자
- 두 행렬을 그냥 곱하고 싶을 때는 @ 연산자를 사용하면 됩니다. 행렬 A와 B를 곱해볼게요.

In [10]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

B = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])


In [11]:
A @ B

array([[12, 24, 36, 48, 60],
       [13, 26, 39, 52, 65],
       [12, 24, 36, 48, 60],
       [12, 24, 36, 48, 60]])

numpy 기본 함수들

np.sum 함수
- np.sum함수는 파라미터로 넘겨주는 행렬 안에 있는 모든 원소들의 합을 구해주는 함수입니다.

In [12]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

np.sum(A)

49

그렇지만 행렬 안에 nan 값이 있으면 항상 np.sum 함수도 nan을 리턴하는데요. nan 값들만 제외하고 계산을 하고 싶을 때는 np.nansum이라는 함수를 사용하면 됩니다.

In [13]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, np.nan, 3, 1],
    [3, 1, 4, 3, 1],
])

np.nansum(A)

47.0

이렇게 nan을 제외한 다른 모든 원소들의 합이 리턴되죠. 이번 토픽에서는 이 np.nansum 함수를 사용하니까 어떤 의미인지 잊지 마세요!

np.mean 함수
- np.mean 함수는 행렬의 모든 원소들의 평균 값을 계산해 주는 함수입니다.

In [14]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

np.mean(A)

2.45

이렇게 말이죠. np.sum과 마찬가지로 원소 중 단 한 개라도 nan 값이면 결과도 nan이 되는데요. 그럴 때는 똑같이, np.nanmean 함수를 사용할 수 있습니다. nan인 원소를 제외한 다른 모든 원소들의 평균값을 계산할 수 있죠. 이렇게요:

In [15]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, np.nan, 3, 1],
    [3, 1, 4, 3, 1],
])

np.nanmean(A)

2.473684210526316

numpy 행렬 접근법

기본 인덱스 접근법
- numpy 행렬 안에 있는 세부 데이터는 인덱스를 사용해서 접근합니다.
- 예를 들어 A의 0 번째 행에 접근하고 싶으면, A[0], 3 번째 행에 접근하고 싶으면 A[3] 이렇게요.

In [17]:
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

print(A[0])  # array([3, 3, 2, 3, 1]) 리턴
print(A[3])  # array([3, 1, 4, 3, 1]) 리턴

[3 3 2 3 1]
[3 1 4 3 1]


그리고 0 행 2열에 접근하고 싶을 때는 A[0][3]. 1행 1열에는 A[1][1] 이렇게 해주면 되죠. 쉽죠?

열 접근법
- 그럼 열에 접근하고 싶으면 어떻게 할까요? 3열에 접근하고 싶을 때는 이렇게 하면 되죠. A[:, 3]

In [18]:
A[:, 3]  # array([3, 3, 3, 3])`

array([3, 3, 3, 3])

In [19]:
A[3, :]  # array([3, 1, 4, 3, 1]) 리턴

array([3, 1, 4, 3, 1])